name: Build & Deploy Image

on:
  push:
    branches: [main]
    paths-ignore:
      - 'deployment.yaml'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
        # git clone https://github.com/yourname/your-repo.git
        # cd your-repo
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version tag (timestamp)
        id: tag
        run: echo "value=$(date +'%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT
        # VERSION=2025-12-11-143025
        # Image name: 
        # mdmudsfikurrahamn/hello-world:2025-12-11-090512

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello:${{ steps.tag.outputs.value }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello:${{ steps.tag.outputs.value }}

      - name: Update deployment.yaml and commit
        run: |
          sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/flask-hello:${{ steps.tag.outputs.value }}|" deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Deploy new image ${{ steps.tag.outputs.value }}"
          git push